---

- name: detect package name httpd
  set_fact:
    ansible_package_name: httpd
  when:  ansible_web_engine is match("apache2|httpd")


- name: install web engine httpd
  yum:
    name: '{{ ansible_package_name }}'
    state: latest
    update_cache: yes
  when: ansible_web_engine is match("apache2|httpd")
  notify:
    - include vars
    - config web engine httpd


- name: detect package name nginx
  set_fact:
    ansible_package_name: nginx
  when:  ansible_web_engine is match("nginx")


- name: Add NGINX repository on Redhat
  yum_repository:
    name: nginx
    description: nginx repo
    baseurl: https://nginx.org/packages/mainline/{{ ansible_distribution|lower }}/{{ ansible_distribution_major_version }}/$basearch/
    gpgcheck: no
    enabled: yes
    file: nginx
  notify:
    - include vars
    - install web engine nginx on Redhat
