---
# tasks file for ws
- name: detect os for install web engine
  import_tasks: ansible_pkg_mgr_debian.yml
  when:
    - ansible_pkg_mgr == 'apt'
- import_tasks: ansible_pkg_mgr_redhat.yml
  when:
    - ansible_pkg_mgr == 'yum'