---

- name: install php packages on Redhat
  yum:
    name: '{{ item }}'
    state: latest
    update_cache: yes
  with_items:
    - php
    - php-mbstring
    - php-pear
    - php-fpm
    - php-mysql
  notify:
    - config php on Redhat


- name: restart php-fpm on Redhat
  service:
    enabled: yes
    name: php-fpm
    state: restarted