---

- name: Add specified repository into sources list on Debian
  apt_repository:
    repo: '{{ item }}'
    state: present
    filename: nginx.repo
  with_items:
    - deb https://nginx.org/packages/mainline/ubuntu/ {{ ansible_distribution_release }} nginx
    - deb-src https://nginx.org/packages/mainline/ubuntu/ {{ ansible_distribution_release }} nginx
  notify: install web engine nginx on Debian


- name: install web engine nginx on Debian
  apt:
    force: yes
    install_recommends: yes
    name: '{{ ansible_package_name }}'
    state: latest
    update_cache: yes
  when:  ansible_web_engine is match("nginx")
  notify:
    - initialing virtual domain
    - restart web engine


- name: install web engine nginx on Redhat
  yum:
    name: '{{ ansible_package_name }}'
    state: latest
    update_cache: yes
  when: ansible_web_engine is match("nginx")
  notify:
    - initialing virtual domain
    - allow http service
    - restart web engine


- name: allow http service
  firewalld:
    immediate: yes
    permanent: yes
    service: '{{ item }}'
    state: enabled
  with_items:
    - http
    - https


- name: initialing virtual domain
  template:
    backup: yes
    src: 'nginx_wordpress.conf.j2'
    dest: '/etc/nginx/conf.d/wordpress.conf'