---
# handlers file for ws

- name: include vars
  include_vars:
    file: ../../wp/vars/main.yml


- include: handlers_apache2.yml
- include: handlers_httpd.yml
- include: handlers_nginx.yml


- name: restart web engine
  service:
    name: '{{ ansible_package_name }}'
    enabled: yes
    state: restarted
